# General config
base_url = "https://blog.imbleau.com"
title = "Spencer C. Imbleau"
description = "Insights on modern technology."
default_language = "en"
theme = "abridge"
output_dir = "public"
compile_sass = true
build_search_index = true
minify_html = true
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

# Footer social links; full options listed in macros/social.html
[extra.social]
feed = true
mail = "spencer@imbleau.com"
twitter = "spencerimbleau"
linkedin = "simbleau"
github = "simbleau"
github_sponsor = "simbleau"
buymeacoffee = "simbleau"
researchgate = "Spencer-Imbleau"

[extra]
language_code = "en-US"
title_separator = "|"  # Separator between title and title_addition, set as |, -, _, etc
author = "Spencer C. Imbleau"
author_show = false # displays the author name below the title after the date, tags, categories
readtime = true # displays the read time on line with date, tags, categories
readtime_string = "min read" # read time indication eg "min": - 1 min  "min read": - 1 min read
recent = true
recent_items = 6
footer_credit = true
footer_credit_override = 'Built with <i class="fa-solid fa-mug-hot"></i> and a <i class="fa-solid fa-keyboard"></i> using <i class="fa-brands fa-rust"></i><br><small><a href="https://github.com/simbleau/simbleau.github.io"><i class="fa-solid fa-pen-to-square"></i> Edit on GitHub</a></small>'

textlogo = 'Spencer C. Imbleau'
title_addition = "Blog" # a default value for title addition
sitedesc = false # enables or disables the display of the site description below the logo.
copyright_start_year = 2021  # optional
#copyright_end_year = 2020  # optional, recommend leaving unset, zola build will set this to current year by default

headhr = true # show or hide horizontal rule below header
foothr = true # show or hide horizontal rule above footer
menu = [
    {url = "/", name = '<i class="fa-solid fa-house"></i> Home', slash = true},
    {url = "/donate/", name = '<i class="fa-solid fa-circle-dollar-to-slot"></i> Donate', slash = true},
    {url = "/posts/", name = '<i class="fa-solid fa-book"></i> Posts', slash = true},
    {url = "/categories/", name = '<i class="fa-solid fa-layer-group"></i> Categories', slash = true},
    {url = "/tags/", name = '<i class="fa-solid fa-tags"></i> Tags', slash = true},
]
menu_footer = [
    {url = "/", name = '<i class="fa-solid fa-house"></i> Home', slash = true},
    {url = "/about/", name = '<i class="fa-solid fa-circle-info"></i> About', slash = true},
    {url = "/privacy/", name = '<i class="fa-solid fa-user-secret"></i> Privacy', slash = true},
    {url = "/sitemap.xml", name = '<i class="fa-solid fa-map-location-dot"></i> Sitemap', slash = false},
]

# SEO
seo = true  # enable or disable seo-related meta tags: opengraph, facebook, twitter
twitter = "spencerimbleau"
keywords = "blog, kubernetes, k8s, cloud, rust"
#google = "Your Google Site verification code."
#bing = "Your Bing Site verification code."
banner = "banner.png" # Used for embedding cards

# Favicons
favicon_theme_color = "#fafafa"
favicon_ms_color = "#fafafa"
favicon_webmanifest = "site.webmanifest" # Used for android-chrome-512x512.png and android-chrome-192x192.png
# TODO favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
# TODO favicon_mask_color = "#ff9900"
favicon180 = "apple-touch-icon.png" # apple-touch-icon.png
favicon32 = "favicon-32x32.png" # favicon-32x32.png
favicon16 = "favicon-16x16.png" # favicon-16x16.png

# Resources
fontawesome = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/all.min.css"
stylesheet = "abridge-bluelight.css" # location and file to use for stylesheet
js_search_index ="search_index.en.js"
js_search = "search.min.js"

# For externally loaded Fonts, make sure to include the FULL url including the http/https prefix
#fonts = [ {url = "https://fonts.googleapis.com/css?family=Montserrat:400,700,italic|Fira+Code:400,italic"} ]

# Local fonts are defined in the css, defining them here only adds the preload tag to the head.
# preload will eliminate Content Layout Shift, but will hurt with page load time.
#fonts = [
#    {url = "font/FiraCode.woff2"},
#    {url = "font/Jost.woff2"},
#    {url = "font/Jost-italic.woff2"},
#    {url = "font/Jost-Bold.woff2"},
#]

# Security Headers should preferably be set by your webserver (Nginx, Apache) https://observatory.mozilla.org
# Set this to true if you are unable to load your security headers with your webserver, this will load a couple of them as meta tags.
# There are many other security related headers most of which can only be set by the webserver method.
security_header_referrer = "strict-origin-when-cross-origin"

math = false # used to to render mathematical notations, requires js
math_auto_render = false

[markdown]
highlight_code = true
highlight_theme = "ayu-light-abridge" # OneHalfDark, material-dark, ayu-dark, Midnight.dark
#highlight_theme = "css" # use css classes - https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting
render_emoji = true
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc
extra_syntaxes_and_themes = ["themes/abridge/highlight_themes"]