base_url = "https://spencer.imbleau.com/blog/"
title = "Spencer C. Imbleau"
description = "Human factoring for non-human issues"
default_language = "en"
theme = "abridge"

output_dir = "public"
compile_sass = true
build_search_index = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
#ignored_content = ["*.{graphml,xlsx}", "temp.*"]
#hard_link_static = false # set to true to hard link instead of copying, useful for very large files.
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "material-dark" # OneHalfDark, material-dark, ayu-dark, Midnight.dark
#highlight_theme = "css" # use css classes - https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting
render_emoji = true
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

[extra]
katex_enable = false # used to to render mathematical notations, requires js
katex_auto_render = false
recent = true
recent_items = 6
footer_credit = false
#google = "Your Google Site verification code."
#bing = "Your Bing Site verification code."
textlogo = 'Spencer C. Imbleau'
sitedesc = false # enables or disables the display of the site description below the logo.
author = "Spencer C. Imbleau"
favicon = "favicon.ico"
banner = "card.png"
menu = [
    {url = "/", name = "Home", slash = true},
    {url = "/about/", name = "About", slash = true},
    {url = "/posts/", name = "Posts", slash = true},
    {url = "/categories/", name = "Categories", slash = true},
    {url = "/tags/", name = "Tags", slash = true},
]
menu_footer = [
    {url = "/", name = "Home", slash = true},
    {url = "/about/", name = "About", slash = true},
    {url = "/privacy/", name = "Privacy", slash = true},
    {url = "/sitemap.xml", name = "Sitemap", slash = false},
]
copyright_start_year = 2021  # optional
#copyright_end_year = 2020  # optional, recommend leaving unset, zola build will set this to current year by default

# meta tags
keywords = "blog, kubernetes, k8s, cloud, rust"
twitter = "spencerimbleau"
seo = true  # enable or disable seo-related meta tags: opengraph, facebook, twitter

# Footer social links; full options listed in macros/social.html
[extra.social]
feed = true
mail = "spencer@imbleau.com"
twitter = "spencerimbleau"
linkedin = "simbleau"
github = "simbleau"
youtube = "UCj9vVqSQlGZbU0c8Dtnpgug"